# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Andrei Popescu
description: popescuaaa
github_username: popescuaaa

# Email and twitter are optional:
email: andreigabrielpopescu556@gmail.com
twitter_username: popescuaaa

social_links:
  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
